questions = [
    {"q": "Who is best?\n1. Hinata\n2. Sakura", "answer": "1"},
    {"q": "Who's cooler?\n1. Itachi\n2. Sasuke", "answer": "1"},
    {"q": "Cutest demon girl?\n1. Nezuko\n2. Esdeath", "answer": "1"},
    {"q": "Most elegant?\n1. Aqua\n2. Yor Forger", "answer": "2"},
    {"q": "Who would win in a fight?\n1. Mikasa\n2. Rem", "answer": "1"},
    {"q": "Which waifu has pink hair?\n1. Mikasa\n2. Zero Two", "answer": "2"},
    {"q": "Who deserves more love?\n1. Orihime\n2. Sakura", "answer": "1"},
    {"q": "Best 'useless' waifu?\n1. Aqua\n2. Sakura", "answer": "1"},
    {"q": "Who has big chest?\n1. Nami\n2. T.Sunade", "answer": "2"},
    {"q": "Strongest fighter?\n1. Erza Scarlet\n2. Mikasa Ackerman", "answer": "1"},
    {"q": "Cutest maid?\n1. Rem\n2. Ram", "answer": "1"},
    {"q": "Who is more loyal?\n1. Hinata Hyuga\n2. Asuna Yuuki", "answer": "1"},
    {"q": "Best archer?\n1. Sinon\n2. Yona", "answer": "1"},
    {"q": "Most mysterious?\n1. Rei Ayanami\n2. Homura Akemi", "answer": "2"},
    {"q": "Who has blue hair?\n1. Aqua\n2. Bulma", "answer": "1"},
    {"q": "Fiercest warrior?\n1. Annie Leonhart\n2. Ymir", "answer": "1"},
    {"q": "Sweetest smile?\n1. Ochaco Uraraka\n2. Momo Yaoyorozu", "answer": "1"},
    {"q": "Who would win a race?\n1. Speed o' Sound Sonic\n2. Saitama", "answer": "2"},
    {"q": "Best cook?\n1. Sanji\n2. Megumi Tadokoro", "answer": "2"},
    {"q": "Most powerful mage?\n1. Megumin\n2. Darkness", "answer": "1"},
    {"q": "Who deserves a hug?\n1. Emilia\n2. Beatrice", "answer": "1"},
    {"q": "Cutest tsundere?\n1. Asuka Langley\n2. Taiga Aisaka", "answer": "2"},
    {"q": "Who has long hair?\n1. Raphtalia\n2. Shiro", "answer": "1"},
    {"q": "Bravest hero?\n1. Deku\n2. Tanjiro Kamado", "answer": "2"},
    {"q": "Most stylish?\n1. Boa Hancock\n2. Nico Robin", "answer": "1"},
    {"q": "Who is smarter?\n1. Light Yagami\n2. L", "answer": "2"},
    {"q": "Best dancer?\n1. Mitsuri Kanroji\n2. Shinobu Kocho", "answer": "1"},
    {"q": "Who would win in chess?\n1. Lelouch vi Britannia\n2. Shikamaru Nara", "answer": "1"},
    {"q": "Cutest animal girl?\n1. Felicia\n2. Holo", "answer": "2"},
    {"q": "Most elegant swordswoman?\n1. Saber\n2. Rukia Kuchiki", "answer": "1"},
    {"q": "Who has green eyes?\n1. C.C.\n2. Erza Scarlet", "answer": "1"},
    {"q": "Strongest villain?\n1. Madara Uchiha\n2. All For One", "answer": "1"},
    {"q": "Best singer?\n1. Miku Hatsune\n2. Sheryl Nome", "answer": "1"},
    {"q": "Who deserves more screen time?\n1. Winry Rockbell\n2. Riza Hawkeye", "answer": "1"},
    {"q": "Most adventurous?\n1. Lucy Heartfilia\n2. Natsu Dragneel", "answer": "1"},
    {"q": "Who is funnier?\n1. Gintoki Sakata\n2. Kagura", "answer": "1"},
    {"q": "Cutest childhood friend?\n1. Chi-Chi\n2. Bulma", "answer": "1"},
    {"q": "Who has fire powers?\n1. Natsu Dragneel\n2. Portgas D. Ace", "answer": "2"},
    {"q": "Most caring?\n1. Chihiro\n2. Tohru Honda", "answer": "2"},
    {"q": "Who would win a debate?\n1. Senku Ishigami\n2. Armin Arlert", "answer": "1"},
    {"q": "Best mechanic?\n1. Winry Rockbell\n2. Bulma Briefs", "answer": "2"},
    {"q": "Who has purple hair?\n1. Yoruichi Shihouin\n2. Blair", "answer": "1"},
    {"q": "Most determined?\n1. Eren Yeager\n2. Gon Freecss", "answer": "1"},
    {"q": "Cutest witch?\n1. Iroha Tamaki\n2. Atsuko Kagari", "answer": "2"},
    {"q": "Who is more heroic?\n1. All Might\n2. Captain America", "answer": "1"},
    {"q": "Best thief?\n1. Lupin III\n2. Catwoman", "answer": "1"},
    {"q": "Who has better aim?\n1. Usopp\n2. Yoko Littner", "answer": "2"},
    {"q": "Most graceful?\n1. Inori Yuzuriha\n2. Euphemia li Britannia", "answer": "1"},
    {"q": "Who deserves a happy ending?\n1. Subaru Natsuki\n2. Kazuma Satou", "answer": "1"},
    {"q": "Cutest robot girl?\n1. Alisa Bosconovitch\n2. Chii", "answer": "2"},
    {"q": "Who has wind powers?\n1. Wendy Marvell\n2. Temari", "answer": "1"},
    {"q": "Most optimistic?\n1. Monkey D. Luffy\n2. Naruto Uzumaki", "answer": "2"},
    {"q": "Best strategist?\n1. Erwin Smith\n2. Roy Mustang", "answer": "1"},
    {"q": "Who is tougher?\n1. Revy\n2. Balalaika", "answer": "2"},
    {"q": "Cutest vampire?\n1. Shinobu Oshino\n2. Krul Tepes", "answer": "1"},
    {"q": "Who has ice powers?\n1. Gray Fullbuster\n2. Toshiro Hitsugaya", "answer": "2"},
    {"q": "Most creative?\n1. Joseph Joestar\n2. Okabe Rintarou", "answer": "1"},
    {"q": "Best pilot?\n1. Shinji Ikari\n2. Kamina", "answer": "2"},
    {"q": "Who deserves more respect?\n1. Vegeta\n2. Piccolo", "answer": "1"}
]

questions1 = [
    {"q": "Who is best?\n1. Hinata\n2. Sakura", "answer": "1"},
    {"q": "Who's cooler?\n1. Itachi\n2. Sasuke", "answer": "1"},
    {"q": "Cutest demon girl?\n1. Nezuko\n2. Esdeath", "answer": "1"},
    {"q": "Most elegant?\n1. Aqua\n2. Yor Forger", "answer": "2"},
    {"q": "Who would win in a fight?\n1. Mikasa\n2. Rem", "answer": "1"},
    {"q": "Which waifu has pink hair?\n1. Mikasa\n2. Zero Two", "answer": "2"},
    {"q": "Who deserves more love?\n1. Orihime\n2. Sakura", "answer": "1"},
    {"q": "Best 'useless' waifu?\n1. Aqua\n2. Sakura", "answer": "1"},
    {"q": "Who has big chest?\n1. Nami\n2. T.Sunade", "answer": "2"},
    {"q": "Strongest Sorcerer?\n1. Gojo Satoru\n2. Sukuna", "answer": "1"},
    {"q": "Best Tsundere?\n1. Rin Tohsaka\n2. Taiga Aisaka", "answer": "2"},
    {"q": "Who is smarter?\n1. L Lawliet\n2. Light Yagami", "answer": "1"},
    {"q": "Which one is a 'One Punch Man'?\n1. Genos\n2. Saitama", "answer": "2"},
    {"q": "Better Swordsman?\n1. Zoro\n2. Kirito", "answer": "1"},
    {"q": "Most loyal shadow?\n1. Beru\n2. Igris", "answer": "2"},
    {"q": "Who is the 'Ice Queen'?\n1. Esdeath\n2. Rukia", "answer": "1"},
    {"q": "Best Maid?\n1. Rem\n2. Tohru", "answer": "1"},
    {"q": "Who has the Geass?\n1. Lelouch\n2. Suzaku", "answer": "1"},
    {"q": "Scarier villain?\n1. Frieza\n2. Madara", "answer": "2"},
    {"q": "Better Cook?\n1. Sanji\n2. Soma Yukihira", "answer": "1"},
    {"q": "The 'Copy Ninja'?\n1. Kakashi\n2. Obito", "answer": "1"},
    {"q": "Cutest Spy x Family character?\n1. Anya\n2. Yor", "answer": "1"},
    {"q": "Who is the 'Dragon Slayer'?\n1. Natsu\n2. Gray", "answer": "1"},
    {"q": "Best 'Mommy' energy?\n1. Makima\n2. Mitsuri Kanroji", "answer": "1"},
    {"q": "More badass captain?\n1. Levi Ackerman\n2. Erwin Smith", "answer": "1"},
    {"q": "Which one uses blue flames?\n1. Dabi\n2. Todoroki", "answer": "1"},
    {"q": "Best Waifu with glasses?\n1. Hanekawa\n2. Mirai Kuriyama", "answer": "2"},
    {"q": "Who is the 'King of Curses'?\n1. Mahito\n2. Sukuna", "answer": "2"},
    {"q": "The 'Yellow Flash' of the Leaf?\n1. Minato\n2. Naruto", "answer": "1"},
    {"q": "Best Ghost Girl?\n1. Miko Yotsuya\n2. Perona", "answer": "2"},
    {"q": "Who is 'Number 1 Hero'?\n1. Endeavor\n2. All Might", "answer": "2"},
    {"q": "Most chaotic sister?\n1. Shinobu\n2. Nezuko", "answer": "1"},
    {"q": "Best 'Kuudere'?\n1. Mikasa\n2. Rei Ayanami", "answer": "2"},
    {"q": "Who has the 'Death Note'?\n1. Ryuk\n2. Misa Amano", "answer": "1"},
    {"q": "Strongest Female Titan?\n1. Annie\n2. Pieck", "answer": "1"},
    {"q": "Which one is a Vampire?\n1. Krul Tepes\n2. Seras Victoria", "answer": "1"},
    {"q": "Best 'Bro' character?\n1. Speedwagon\n2. Kamina", "answer": "1"},
    {"q": "Who is the 'Symbol of Peace'?\n1. Deku\n2. All Might", "answer": "2"},
    {"q": "Better Archer?\n1. Archer (Emiya)\n2. Uryu Ishida", "answer": "1"},
    {"q": "Which one is 'Zero Two'?\n1. Ichigo\n2. 002", "answer": "2"},
    {"q": "Most annoying fairy?\n1. Navi\n2. Puck", "answer": "1"},
    {"q": "Best 'Red Flag' waifu?\n1. Makima\n2. Yuno Gasai", "answer": "2"},
    {"q": "Who is the 'Ghost of the Uchiha'?\n1. Madara\n2. Itachi", "answer": "1"},
    {"q": "Better Pirate King candidate?\n1. Luffy\n2. Blackbeard", "answer": "1"},
    {"q": "Who is the 'Humanoid Typhoon'?\n1. Vash\n2. Wolfwood", "answer": "1"},
    {"q": "Which one is the 'Alchemist'?\n1. Edward Elric\n2. Roy Mustang", "answer": "1"},
    {"q": "Best 'Short King'?\n1. Levi\n2. Edward Elric", "answer": "1"},
    {"q": "Most wholesome couple?\n1. Loid & Yor\n2. Shikimori & Izumi", "answer": "1"},
    {"q": "Who is 'The Gamer'?\n1. Kirito\n2. Sora", "answer": "1"}
]


